config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  resources :patient_records do
    resources :attachments
    resources :comments
    resources :treatments do
      resources :drugs
    end
    member do
      put :assign_to_doctor
    end
  end
  resources :general_drugs

  resources :my_patients
  resources :home, only: [:index]

  namespace :patient do
    resources :patient_records do
      resources :treatments, only: [:show]
    end
  end

  namespace :nurse do
    resources :general_drugs
    resources :my_patients
    resources :patient_records do
      resources :attachments
      resources :comments
      resources :treatments do
        resources :drugs
      end
      member do
        put :assign_to_nurse
      end
    end
  end

  root "home#index"
end

app/models/treatment.rb
class Treatment < ApplicationRecord
  belongs_to :patient_record
  belongs_to :doctor, class_name: "User", foreign_key: :doctor_id

  has_many :treatment_drugs, dependent: :destroy
  has_many :drugs, through: :treatment_drugs

  enum status: [:in_progress, :completed]

  validates_presence_of :description

  before_create :set_date

  def set_date
    self.date = Date.current
  end
end

app/controllers/nurse/treatments_controller.rb
class Nurse::TreatmentsController < Nurse::ApplicationController
  before_action :set_patient_record
  before_action :set_treatment, only: [:show, :destroy, :update, :edit]

  def new
    @treatment = @patient_record.treatments.new
  end

  def create
    @treatment = @patient_record.treatments.new(treatments_params)
    @treatment.doctor = current_user

    if @treatment.save
      redirect_to nurse_my_patient_path(@patient_record), notice: "Treatment added successfully."
    else
      redirect_to nurse_my_patients_path, alert: @treatment.errors.full_messages.join(", ")
    end
  end

  def show; end

  def edit; end

  def update
    if @treatment.update(treatments_params)
      redirect_to nurse_my_patient_path(@patient_record), notice: "Treatment updated successfully."
    else
      redirect_to nurse_my_patients_path, alert: @treatment.errors.full_messages.join(", ")
    end
  end

  def destroy
    if @treatment.destroy
      redirect_to nurse_my_patient_path(@patient_record), notice: "Treatment destroyed successfully."
    else
      redirect_to nurse_my_patients_path, alert: @treatment.errors.full_messages.join(", ")
    end
  end

  private

  def treatments_params
    params.require(:treatment).permit(:description, :status)
  end

  def set_treatment
    @treatment = @patient_record.treatments.find(params[:id])
  end

  def set_patient_record
    @patient_record = PatientRecord.find(params[:patient_record_id])
  end
end

app/controllers/patient/treatments_controller.rb
class Patient::TreatmentsController < Patient::ApplicationController
  def show
    @treatment = Treatment.find(params[:id])
  end
end

app/controllers/treatments_controller.rb
class TreatmentsController < ApplicationController
  before_action :set_patient_record
  before_action :set_treatment, only: [:show, :destroy, :update, :edit]

  def new
    @treatment = @patient_record.treatments.new
  end

  def create
    @treatment = @patient_record.treatments.new(treatments_params)
    @treatment.doctor = current_user

    if @treatment.save
      redirect_to my_patient_path(@patient_record), notice: "Treatment added successfully."
    else
      redirect_to my_patients_path, alert: @treatment.errors.full_messages.join(", ")
    end
  end

  def show; end

  def edit; end

  def update
    if @treatment.update(treatments_params)
      redirect_to my_patient_path(@patient_record), notice: "Treatment updated successfully."
    else
      redirect_to my_patients_path, alert: @treatment.errors.full_messages.join(", ")
    end
  end

  def destroy
    if @treatment.destroy
      redirect_to my_patient_path(@patient_record), notice: "Treatment destroyed successfully."
    else
      redirect_to my_patients_path, alert: @treatment.errors.full_messages.join(", ")
    end
  end

  private

  def treatments_params
    params.require(:treatment).permit(:description, :status)
  end

  def set_treatment
    @treatment = @patient_record.treatments.find(params[:id])
  end

  def set_patient_record
    @patient_record = PatientRecord.find(params[:patient_record_id])
  end
end

app/helpers/treatments_helper.rb
module TreatmentsHelper
end

app/views/treatments/_form.html.erb
<%= simple_form_for @treatment, url: @treatment.new_record? ? patient_record_treatments_path : patient_record_treatment_path(@treatment), html: { "data-turbo": false, class: "row g-3" } do |f| %>

  <div class="col-12">
    <label class="form-label">Description</label>
    <%= f.input :description, input_html: { class: "form-control" }, label: false %>
  </div>

  <div class="col-12">
    <%= f.button :submit, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/treatments/edit.html.erb
<div class="card">
  <div class="card-body">
    <h5 class="card-title">Edit treatment</h5>

    <%= render "treatments/form" %>
  </div>
</div>

app/views/treatments/new.html.erb
<div class="card">
  <div class="card-body">
    <h5 class="card-title">New Treatment</h5>

    <%= render "treatments/form" %>
  </div>
</div>

app/views/treatments/show.html.erb
<div class="card">
  <div class="card-body">
    <h5 class="card-title">Drugs</h5>

    <%= link_to "New Drug", new_patient_record_treatment_drug_path(@treatment.patient_record, @treatment), class: "btn btn-primary float-end" %>

    <!-- Default Table -->
    <table class="table">
      <thead>
      <tr>
        <th scope="col">Drug name</th>
        <th scope="col">Description</th>
        <th colspan="2">Actions</th>
      </tr>
      </thead>
      <tbody>
      <% @treatment.treatment_drugs.each do |treatment_drug| %>
        <tr>
          <td><%= treatment_drug.drug.name %></td>
          <td><%= treatment_drug.description %></td>
          <td>
            <%= link_to "Edit", edit_patient_record_treatment_drug_path(@treatment.patient_record, @treatment, treatment_drug.drug), class: "btn btn-sm btn-primary" %>
            <a class="btn btn-sm btn-outline-danger" href="/patient_records/<%= @treatment.patient_record.id %>/treatments/<%= @treatment.id %>/drugs/<%= treatment_drug.id  %>">Delete</a>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>