config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  resources :patient_records do
    resources :attachments
    resources :comments
    resources :treatments do
      resources :drugs
    end
    member do
      put :assign_to_doctor
    end
  end
  resources :general_drugs

  resources :my_patients
  resources :home, only: [:index]

  namespace :patient do
    resources :patient_records do
      resources :treatments, only: [:show]
    end
  end

  namespace :nurse do
    resources :general_drugs
    resources :my_patients
    resources :patient_records do
      resources :attachments
      resources :comments
      resources :treatments do
        resources :drugs
      end
      member do
        put :assign_to_nurse
      end
    end
  end

  root "home#index"
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/attachment.rb
require 'base64'
class Attachment < ApplicationRecord
  belongs_to :patient_record

  has_one_attached :file

  has_one_attached :image

  has_many :drug_attachments, dependent: :destroy
  has_many :drugs, through: :drug_attachments

  accepts_nested_attributes_for :drugs

  after_create :decrease_count

  def decrease_count
    self.drugs.each do |drug|
      drug.update_column(:stock, (drug.stock - 1))
    end
  end

  def wicked_blob_path
    path = ActiveStorage::Blob.service.send(:path_for, self.image.blob.key)
    Base64.encode64(File.open(path, "rb").read)
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :patient_record

  before_create :set_date

  def set_date
    self.added_at = DateTime.current
  end
end

app/models/drug.rb
class Drug < ApplicationRecord

  has_many :treatment_drugs, dependent: :destroy
  has_many :treatments, dependent: :destroy

  has_many :drug_attachments, dependent: :destroy
  has_many :attachments, through: :drug_attachments
end

app/models/drug_attachment.rb
class DrugAttachment < ApplicationRecord
  belongs_to :drug
  belongs_to :attachment
end

app/models/patient_record.rb
class PatientRecord < ApplicationRecord
  belongs_to :user

  enum status: [:not_started, :in_progress, :cured]

  has_many :user_patient_records, dependent: :destroy
  has_many :users, through: :user_patient_records
  has_many :comments, dependent: :destroy
  has_many :treatments, dependent: :destroy
  has_many :attachments, dependent: :destroy
end

app/models/role.rb
class Role < ApplicationRecord

  validates_presence_of :name
  validates_uniqueness_of :name
  has_many :users

  before_save :set_slug


  def set_slug
    self.slug = self.name.downcase
  end
end

app/models/treatment.rb
class Treatment < ApplicationRecord
  belongs_to :patient_record
  belongs_to :doctor, class_name: "User", foreign_key: :doctor_id

  has_many :treatment_drugs, dependent: :destroy
  has_many :drugs, through: :treatment_drugs

  enum status: [:in_progress, :completed]

  validates_presence_of :description

  before_create :set_date

  def set_date
    self.date = Date.current
  end
end

app/models/treatment_drug.rb
class TreatmentDrug < ApplicationRecord
  belongs_to :drug
  belongs_to :treatment
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  belongs_to :role
  has_many :patient_records, dependent: :destroy
  has_many :user_patient_records, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :patient_records, through: :user_patient_records
end

app/models/user_patient_record.rb
class UserPatientRecord < ApplicationRecord
  belongs_to :user
  belongs_to :patient_record
end

app/controllers/drugs_controller.rb
class DrugsController < ApplicationController
  before_action :set_treatment
  before_action :set_treatment_drug, only: [:edit, :update, :destroy]

  def new
    @treatment_drug = TreatmentDrug.new
  end

  def create
    @treatment_drug = TreatmentDrug.new(drugs_params)
    @treatment_drug.treatment = @treatment

    if @treatment_drug.save
      redirect_to patient_record_treatment_path(@treatment_drug.treatment.patient_record, @treatment_drug.treatment), notice: "Drug added successfully."
    else
      redirect_to patient_record_treatment_path(@treatment_drug.treatment.patient_record, @treatment_drug.treatment), alert: @treatment_drug.errors.full_messages.join(",")
    end
  end

  def edit; end

  def update
    if @treatment_drug.update(drugs_params)
      redirect_to patient_record_treatment_path(@treatment_drug.treatment.patient_record, @treatment_drug.treatment), notice: "Drug updated successfully."
    else
      redirect_to patient_record_treatment_path(@treatment_drug.treatment.patient_record, @treatment_drug.treatment), alert: @treatment_drug.errors.full_messages.join(",")
    end
  end

  def destroy
    if @treatment_drug.destroy
      redirect_to patient_record_treatment_path(@treatment_drug.treatment.patient_record, @treatment_drug.treatment), notice: "Drug destroyed successfully."
    else
      redirect_to patient_record_treatment_path(@treatment_drug.treatment.patient_record, @treatment_drug.treatment), alert: @treatment_drug.errors.full_messages.join(",")
    end
  end

  private

  def drugs_params
    params.require(:treatment_drug).permit(:description, :drug_id)
  end

  def set_treatment_drug
    @treatment_drug = TreatmentDrug.find(params[:id])
  end

  def set_treatment
    @treatment = Treatment.find(params[:treatment_id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!
  def index
    if current_user.present?
      if current_user.role.slug == "doctor"
        redirect_to patient_records_path
      elsif current_user.role.slug == "patient"
        redirect_to patient_patient_records_path
      elsif current_user.role.slug == "nurse"
        redirect_to  nurse_patient_records_path
      end
    end
  end
end

app/controllers/my_patients_controller.rb
class MyPatientsController < ApplicationController

  def index
    @patient_records = PatientRecord.includes(:user_patient_records).where(user_patient_records: { user_id: current_user.id}).all
  end

  def show
    @patient_record = PatientRecord.find(params[:id])
  end
end

app/controllers/nurse/my_patients_controller.rb
class Nurse::MyPatientsController < Nurse::ApplicationController

  def index
    @patient_records = PatientRecord.includes(:user_patient_records).where(user_patient_records: { user_id: current_user.id}).all
  end

  def show
    @patient_record = PatientRecord.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def can_pick_patient_as_a_doctor(patient_records)
    record_exists = true
    doctor_count = 0
    patient_records&.all&.each do |record|
      doctor_count += 1 if record.user.role.slug == "doctor"
      record_exists = false if record.patient_record.treatment_city != current_user.city
    end
    if doctor_count >= 1
      record_exists = false
    end

    record_exists
  end

  def can_pick_patient_as_nurse(patient_records)
    record_exists = true
    nurse_count = 0


    patient_records&.all&.each do |record|
      nurse_count += 1 if record.user.role.slug == "nurse"
      record_exists = false if record.patient_record.treatment_city != current_user.city
    end

    record_exists = false if nurse_count >= 3
    record_exists
  end

end

app/helpers/attachments_helper.rb
module AttachmentsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/drugs_helper.rb
module DrugsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/my_patients_helper.rb
module MyPatientsHelper
end

app/helpers/treatments_helper.rb
module TreatmentsHelper
end

app/views/my_patients/index.html.erb
<div class="card">
  <div class="card-body">
    <h5 class="card-title">My Patients</h5>

    <!-- Default Table -->
    <table class="table">
      <thead>
      <tr>
        <th scope="col">Patient Name</th>
        <th scope="col">Patient Address</th>
        <th scope="col">Disease</th>
        <th scope="col">Date of birth</th>
        <th scope="col">Blood group</th>
        <th scope="col">Status</th>
        <th scope="col" colspan="3">Actions</th>
      </tr>
      </thead>
      <tbody>
      <% @patient_records.each do |patient_record| %>
        <tr>
          <th scope="row"><%= patient_record.name %></th>
          <td><%= patient_record.user.city %>,<%= patient_record.user.state %>,<%= patient_record.user.country %></td>
          <td><%= patient_record.disease %></td>
          <td><%= patient_record.date_of_birth %></td>
          <td><%= patient_record.blood_group %></td>
          <td><%= patient_record.status %></td>
          <td>
            <%= link_to "show",  my_patient_path(patient_record), class: "btn btn-sm btn-outline-info" %>
            <%= link_to "Edit", edit_patient_record_path(patient_record), class: "btn btn-sm btn-primary" %>
            <a data-turbo-method="delete" class="btn btn-sm btn-outline-danger" href="/patient_records/<%= patient_record.id %>">Delete</a>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/my_patients/show.html.erb
<div class="card">
  <div class="card-body">
    <h5 class="card-title">Patient Details</h5>

    <div class="row">
      <div class="col-md-2">
        <strong>
          Patient Name
        </strong>
      </div>
      <div class="col-md-10">
        <%= @patient_record.name %>
      </div>
    </div>

    <div class="row mt-3">
      <div class="col-md-2">
        <strong>
          Patient Address
        </strong>
      </div>
      <div class="col-md-10">
        <%= @patient_record.treatment_city %>,<%= @patient_record.treatment_state %>,<%= @patient_record.treatment_country %>
      </div>
    </div>

    <div class="row mt-3">
      <div class="col-md-2">
        <strong>
          Disease
        </strong>
      </div>
      <div class="col-md-10">
        <%= @patient_record.disease %>
      </div>
    </div>

    <div class="row mt-3">
      <div class="col-md-2">
        <strong>
          Blood group
        </strong>
      </div>
      <div class="col-md-10">
        <%= @patient_record.blood_group %>
      </div>
    </div>

    <div class="row mt-3">
      <div class="col-md-2">
        <strong>
          Date of birth
        </strong>
      </div>
      <div class="col-md-10">
        <%= @patient_record.date_of_birth %>
      </div>
    </div>

    <div class="row mt-3">
      <div class="col-md-2">
        <strong>
          Height
        </strong>
      </div>
      <div class="col-md-10">
        <%= @patient_record.height %>
      </div>
    </div>

    <div class="row mt-3">
      <div class="col-md-2">
        <strong>
          Weight
        </strong>
      </div>
      <div class="col-md-10">
        <%= @patient_record.weight %>
      </div>
    </div>

    <div class="row mt-3">
      <div class="col-md-2">
        <strong>
          Bed Id
        </strong>
      </div>
      <div class="col-md-10">
        <%= @patient_record.bed_id %>
      </div>
    </div>

    <div class="row mt-3">
      <div class="col-md-2">
        <strong>
          Treatment Area
        </strong>
      </div>
      <div class="col-md-10">
        <%= @patient_record.treatment_area %>
      </div>
    </div>

    <div class="row mt-3">
      <div class="col-md-2">
        <strong>
          Treatment City
        </strong>
      </div>
      <div class="col-md-10">
        <%= @patient_record.treatment_city %>
      </div>
    </div>

    <div class="row mt-3">
      <div class="col-md-2">
        <strong>
          Treatment Country
        </strong>
      </div>
      <div class="col-md-10">
        <%= @patient_record.treatment_country %>
      </div>
    </div>

  </div>
</div>


<div class="card">
  <div class="card-body">
    <h5 class="card-title">Comments</h5>

    <%= link_to "New Comment", new_patient_record_comment_path(@patient_record), class: "btn btn-primary float-end" %>

    <!-- Default Table -->
    <table class="table">
      <thead>
      <tr>
        <th scope="col">Comment</th>
        <th scope="col">Created Date</th>
        <th scope="col">Created by</th>
        <th colspan="2">Actions</th>
      </tr>
      </thead>
      <tbody>
      <% @patient_record.comments.each do |comment| %>
        <tr>
          <td><%= comment.comment %></td>
          <td><%= comment.added_at.to_datetime %></td>
          <td><%= comment.user&.name %>(<%= comment.user&.role&.name %>)</td>
          <td>
            <% if comment.user == current_user %>
              <%= link_to "Edit", edit_patient_record_comment_path(comment), class: "btn btn-sm btn-primary" %>
              <a class="btn btn-sm btn-outline-danger" href="/patient_records/<%= @patient_record.id %>/comments/<%= comment.id %>">Delete</a>
            <% end %>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

<div class="card">
  <div class="card-body">
    <h5 class="card-title">Treatments</h5>

    <%= link_to "New Treatment", new_patient_record_treatment_path(@patient_record), class: "btn btn-primary float-end" %>

    <!-- Default Table -->
    <table class="table">
      <thead>
      <tr>
        <th scope="col">Description</th>
        <th scope="col">Status</th>
        <th scope="col">Created Date</th>
        <th colspan="3">Actions</th>
      </tr>
      </thead>
      <tbody>
      <% @patient_record.treatments.each do |treatment| %>
        <tr>
          <td><%= treatment.description %></td>
          <td><%= treatment.status %></td>
          <td><%= treatment.date %></td>
          <td>
            <% if treatment.in_progress? %>
              <a data-turbo-method="put" href="/patient_records/<%= @patient_record.id %>/treatments/<%= treatment.id %>?treatment[status]=completed" class="btn btn-sm btn-outline-primary">Mark as cured</a>
            <% end %>
            <%= link_to "Show", patient_record_treatment_path(treatment), class: "btn btn-sm btn-outline-primary" %>
            <%= link_to "Edit", edit_patient_record_treatment_path(treatment), class: "btn btn-sm btn-primary" %>
            <a class="btn btn-sm btn-outline-danger" href="/patient_records/<%= @patient_record.id %>/treatments/<%= treatment.id %>">Delete</a>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>


<div class="card">
  <div class="card-body">
    <h5 class="card-title">Prescriptions</h5>

    <%= link_to "New Prescription", new_patient_record_attachment_path(@patient_record), class: "btn btn-primary float-end" %>

    <!-- Default Table -->
    <table class="table">
      <thead>
      <tr>
        <th scope="col">Name</th>
        <th scope="col">Disease</th>
        <th scope="col">Treatment</th>
        <th scope="col">Created Date</th>
        <th scope="col">Download</th>
      </tr>
      </thead>
      <tbody>
      <% @patient_record.attachments.each do |attachment| %>
        <tr>
          <td><%= attachment.name %></td>
          <td><%= attachment.disease %></td>
          <td><%= attachment.treatment %></td>
          <td><%= attachment.created_at.to_date %></td>
          <td>
            <%= link_to "Download", rails_blob_path(attachment.file, disposition: 'inline'), target: "_blank", class: "btn btn-sm btn-primary" %>
            <%= link_to "Edit", edit_patient_record_attachment_path(@patient_record, attachment), class: "btn btn-sm btn-primary" %>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>