config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  resources :patient_records do
    resources :attachments
    resources :comments
    resources :treatments do
      resources :drugs
    end
    member do
      put :assign_to_doctor
    end
  end
  resources :general_drugs

  resources :my_patients
  resources :home, only: [:index]

  namespace :patient do
    resources :patient_records do
      resources :treatments, only: [:show]
    end
  end

  namespace :nurse do
    resources :general_drugs
    resources :my_patients
    resources :patient_records do
      resources :attachments
      resources :comments
      resources :treatments do
        resources :drugs
      end
      member do
        put :assign_to_nurse
      end
    end
  end

  root "home#index"
end

app/models/patient_record.rb
class PatientRecord < ApplicationRecord
  belongs_to :user

  enum status: [:not_started, :in_progress, :cured]

  has_many :user_patient_records, dependent: :destroy
  has_many :users, through: :user_patient_records
  has_many :comments, dependent: :destroy
  has_many :treatments, dependent: :destroy
  has_many :attachments, dependent: :destroy
end

app/controllers/nurse/application_controller.rb
class Nurse::ApplicationController < ApplicationController
end

app/controllers/nurse/attachments_controller.rb
class Nurse::AttachmentsController < Nurse::ApplicationController
  before_action :set_patient_record
  before_action :set_attachment, only: [:update, :edit, :destroy]

  def new
    @attachment = @patient_record.attachments.new
  end

  def create
    @attachment = @patient_record.attachments.new(attachments_params)

    if @attachment.save
      pdf = WickedPdf.new.pdf_from_string(ActionController::Base.new().render_to_string(template: "attachments/attachment_pdf", layout: 'layouts/pdf', locals: {
        attachment: @attachment
      }))

      @attachment.file.attach(io: StringIO.new(pdf), filename: "file.pdf", content_type: "application/pdf")
      redirect_to nurse_my_patient_path(@patient_record), notice: "Attachment added successfully."
    else
      redirect_to nurse_my_patients_path, alert: @attachment.errors.full_messages.join(", ")
    end
  end

  def edit; end

  def update
    if @attachment.save
      pdf = WickedPdf.new.pdf_from_string(ActionController::Base.new().render_to_string(template: "attachments/attachment_pdf", layout: 'layouts/pdf', locals: {
        attachment: @attachment
      }))

      @attachment.file.attach(io: StringIO.new(pdf), filename: "file.pdf", content_type: "application/pdf")
      redirect_to nurse_my_patient_path(@patient_record), notice: "Attachment added successfully."
    else
      redirect_to nurse_my_patients_path, alert: @attachment.errors.full_messages.join(", ")
    end
  end

  def destroy
    @attachment = @patient_record.attachments.find(params[:id])

    if @attachment.destroy
      redirect_to nurse_my_patient_path(@patient_record), notice: "Attachment destroyed successfully."
    else
      redirect_to nurse_my_patients_path, alert: @attachment.errors.full_messages.join(", ")
    end
  end

  private

  def set_patient_record
    @patient_record = PatientRecord.find(params[:patient_record_id])
  end

  def set_attachment
    @attachment = @patient_record.attachments.find(params[:id])
  end

  def attachments_params
    params.require(:attachment).permit(:name, :address_1, :address_2, :city, :state, :country, :disease, :treatment, :image, drug_ids: [])
  end
end

app/controllers/nurse/comments_controller.rb
class Nurse::CommentsController < Nurse::ApplicationController
  before_action :set_patient_record
  before_action :set_comment, only: [:destroy, :update, :edit]

  def new
    @comment = @patient_record.comments.new
  end

  def create
    @comment = @patient_record.comments.new(comments_params)
    @comment.user = current_user

    if @comment.save
      redirect_to nurse_my_patient_path(@patient_record), notice: "Comment added successfully."
    else
      redirect_to nurse_my_patients_path, alert: @comment.errors.full_messages.join(", ")
    end
  end

  def edit; end

  def update
    if @comment.update(comments_params)
      redirect_to nurse_my_patient_path(@patient_record), notice: "Comment update successfully."
    else
      redirect_to nurse_my_patients_path, alert: @comment.errors.full_messages.join(", ")
    end
  end

  def destroy
    if @comment.destroy
      redirect_to nurse_my_patient_path(@patient_record), notice: "Comment destroyed successfully."
    else
      redirect_to nurse_my_patients_path, alert: @comment.errors.full_messages.join(", ")
    end
  end

  private

  def set_patient_record
    @patient_record = PatientRecord.find(params[:patient_record_id])
  end

  def set_comment
    @comment = @patient_record.comments.find(params[:id])
  end

  def comments_params
    params.require(:comment).permit(:comment)
  end
end

app/controllers/nurse/drugs_controller.rb
class Nurse::DrugsController < Nurse::ApplicationController
  before_action :set_treatment
  before_action :set_treatment_drug, only: [:edit, :update, :destroy]

  def new
    @treatment_drug = TreatmentDrug.new
  end

  def create
    @treatment_drug = TreatmentDrug.new(drugs_params)
    @treatment_drug.treatment = @treatment

    if @treatment_drug.save
      redirect_to nurse_patient_record_treatment_path(@treatment_drug.treatment.patient_record, @treatment_drug.treatment), notice: "Drug added successfully."
    else
      redirect_to nurse_patient_record_treatments_path(@treatment_drug.treatment.patient_record, @treatment_drug.treatment), alert: @treatment_drug.errors.full_messages.join(",")
    end
  end

  def edit; end

  def update
    if @treatment_drug.update(drugs_params)
      redirect_to nurse_patient_record_treatment_path(@treatment_drug.treatment.patient_record, @treatment_drug.treatment), notice: "Drug updated successfully."
    else
      redirect_to nurse_patient_record_treatments_path(@treatment_drug.treatment.patient_record, @treatment_drug.treatment), alert: @treatment_drug.errors.full_messages.join(",")
    end
  end

  def destroy
    if @treatment_drug.destroy
      redirect_to nurse_patient_record_treatment_path(@treatment_drug.treatment.patient_record, @treatment_drug.treatment), notice: "Drug destroyed successfully."
    else
      redirect_to nurse_patient_record_treatments_path(@treatment_drug.treatment.patient_record, @treatment_drug.treatment), alert: @treatment_drug.errors.full_messages.join(",")
    end
  end

  private

  def drugs_params
    params.require(:drug).permit(:description, :drug_id)
  end

  def set_treatment_drug
    @treatment_drug = TreatmentDrug.find(params[:id])
  end

  def set_treatment
    @treatment = Treatment.find(params[:treatment_id])
  end
end

app/controllers/nurse/general_drugs_controller.rb
class Nurse::GeneralDrugsController < Nurse::ApplicationController

  def index
    @general_drugs = Drug.all
  end
end

app/controllers/nurse/my_patients_controller.rb
class Nurse::MyPatientsController < Nurse::ApplicationController

  def index
    @patient_records = PatientRecord.includes(:user_patient_records).where(user_patient_records: { user_id: current_user.id}).all
  end

  def show
    @patient_record = PatientRecord.find(params[:id])
  end
end

app/controllers/nurse/patient_records_controller.rb
class Nurse::PatientRecordsController < Nurse::ApplicationController
  before_action :set_patient_record, only: [:show, :assign_to_nurse, :edit, :update, :destroy]
  def index
    @patient_records = PatientRecord.all
  end

  def new
    @patient_record = PatientRecord.new
  end

  def create
    @patient_record = PatientRecord.new(patient_records_params)
    @patient_record.user = current_user

    if @patient_record.save
      redirect_to nurse_patient_records_path, notice: "Patient record created successfully."
    else
      render :new
    end
  end

  def edit; end

  def update
    if @patient_record.update(patient_records_params)
      redirect_to nurse_patient_records_path, notice: "Patient record updated successfully."
    else
      render :edit
    end
  end


  def show; end

  def assign_to_nurse
    UserPatientRecord.find_or_create_by(user_id: current_user.id, patient_record_id: @patient_record.id)
    @patient_record.update_column(:status, "in_progress")
    redirect_to nurse_my_patients_path, notice: "Patient picked successfully."
  end

  def destroy
    if @patient_record.destroy
      redirect_to nurse_patient_records_path, notice: "Patient record destroyed successfully."
    else
      redirect_to nurse_patient_records_path, alert: @patient_record.errors.full_messages.join(",")
    end
  end

  private

  def set_patient_record
    @patient_record = PatientRecord.find(params[:id])
  end

  def patient_records_params
    params.require(:patient_record).permit(:name, :date_of_birth, :height, :weight, :bed_id, :blood_group, :treatment_area,
                                           :treatment_city, :treatment_state, :treatment_country, :disease, :status)
  end

end

app/controllers/nurse/treatments_controller.rb
class Nurse::TreatmentsController < Nurse::ApplicationController
  before_action :set_patient_record
  before_action :set_treatment, only: [:show, :destroy, :update, :edit]

  def new
    @treatment = @patient_record.treatments.new
  end

  def create
    @treatment = @patient_record.treatments.new(treatments_params)
    @treatment.doctor = current_user

    if @treatment.save
      redirect_to nurse_my_patient_path(@patient_record), notice: "Treatment added successfully."
    else
      redirect_to nurse_my_patients_path, alert: @treatment.errors.full_messages.join(", ")
    end
  end

  def show; end

  def edit; end

  def update
    if @treatment.update(treatments_params)
      redirect_to nurse_my_patient_path(@patient_record), notice: "Treatment updated successfully."
    else
      redirect_to nurse_my_patients_path, alert: @treatment.errors.full_messages.join(", ")
    end
  end

  def destroy
    if @treatment.destroy
      redirect_to nurse_my_patient_path(@patient_record), notice: "Treatment destroyed successfully."
    else
      redirect_to nurse_my_patients_path, alert: @treatment.errors.full_messages.join(", ")
    end
  end

  private

  def treatments_params
    params.require(:treatment).permit(:description, :status)
  end

  def set_treatment
    @treatment = @patient_record.treatments.find(params[:id])
  end

  def set_patient_record
    @patient_record = PatientRecord.find(params[:patient_record_id])
  end
end

app/controllers/patient/patient_records_controller.rb
class Patient::PatientRecordsController < Patient::ApplicationController
  before_action :set_patient_record, only: [:update, :destroy, :show, :edit]

  def index
    @patient_records = PatientRecord.all
  end

  def new
    @patient_record = PatientRecord.new
  end

  def create
    @patient_record = PatientRecord.new(patient_records_params)
    @patient_record.user = current_user

    if @patient_record.save
      redirect_to patient_patient_records_path, notice: "Patient record created successfully."
    else
      render :new
    end
  end

  def edit; end

  def show; end

  def update
    if @patient_record.update(patient_records_params)
      redirect_to patient_patient_records_path, notice: "Patient record updated successfully."
    else
      render :edit
    end
  end

  def destroy
    if @patient_record.destroy
      redirect_to patient_patient_records_path, notice: "Patient record destroyed successfully."
    else
      redirect_to patient_patient_records_path, alert: @patient_record.errors.full_messages.join(",")
    end
  end

  private

  def set_patient_record
    @patient_record = PatientRecord.find(params[:id])
  end

  def patient_records_params
    params.require(:patient_record).permit(:date_of_birth, :height, :weight, :bed_id, :blood_group, :treatment_area,
                                           :treatment_city, :treatment_state, :treatment_country, :disease, :status)
  end
end

app/controllers/patient_records_controller.rb
class PatientRecordsController < ApplicationController
  before_action :set_patient_record, only: [:show, :assign_to_doctor, :edit, :destroy, :update]
  def index
    @patient_records = PatientRecord.all
  end

  def show; end

  def new
    @patient_record = PatientRecord.new
  end

  def create
    @patient_record = PatientRecord.new(patient_records_params)
    @patient_record.user = current_user

    if @patient_record.save
      redirect_to patient_records_path, notice: "Patient record created successfully."
    else
      render :new
    end
  end

  def edit; end

  def assign_to_doctor
    UserPatientRecord.find_or_create_by(user_id: current_user.id, patient_record_id: @patient_record.id)
    @patient_record.update_column(:status, "in_progress")
    redirect_to my_patients_path, notice: "Patient picked successfully."
  end

  def update
    if @patient_record.update(patient_records_params)
      redirect_to patient_records_path, notice: "Patient record updated successfully."
    else
      render :edit
    end
  end

  def destroy
    if @patient_record.destroy
      redirect_to patient_records_path, notice: "Patient record destroyed successfully."
    else
      redirect_to patient_records_path, alert: @patient_record.errors.full_messages.join(",")
    end
  end

  private

  def set_patient_record
    @patient_record = PatientRecord.find(params[:id])
  end

  def patient_records_params
    params.require(:patient_record).permit(:name, :date_of_birth, :height, :weight, :bed_id, :blood_group, :treatment_area,
                                           :treatment_city, :treatment_state, :treatment_country, :disease, :status)
  end
end

app/helpers/patient_records_helper.rb
module PatientRecordsHelper
end

app/views/nurse/patient_records/_form.html.erb
<%= simple_form_for @patient_record, url: @patient_record.new_record? ? nurse_patient_records_path : nurse_patient_record_path(@patient_record), html: { "data-turbo": false, class: "row g-3" } do |f| %>

  <div class="col-12">
    <label class="form-label">Name</label>
    <%= f.input :name, input_html: { class: "form-control" }, label: false %>
  </div>

  <div class="col-12">
    <label class="form-label">Date of birth</label>
    <%= f.input :date_of_birth, input_html: { class: "form-control" }, html5: true, label: false %>
  </div>

  <div class="col-12">
    <label class="form-label">Height</label>
    <%= f.input :height, input_html: { class: "form-control" }, label: false %>
  </div>

  <div class="col-12">
    <label class="form-label">Weight</label>
    <%= f.input :weight, input_html: { class: "form-control" }, label: false %>
  </div>

  <div class="col-12">
    <label class="form-label">Bed Id</label>
    <%= f.input :bed_id, input_html: { class: "form-control" }, label: false %>
  </div>

  <div class="col-12">
    <label class="form-label">Blood Group</label>
    <%= f.input :blood_group, input_html: { class: "form-control" }, label: false %>
  </div>

  <div class="col-12">
    <label class="form-label">Treatment Area</label>
    <%= f.input :treatment_area, input_html: { class: "form-control" }, label: false %>
  </div>

  <div class="col-12">
    <label class="form-label">Treatment City</label>
    <%= f.input :treatment_city, input_html: { class: "form-control" }, label: false %>
  </div>

  <div class="col-12">
    <label class="form-label">Treatment State</label>
    <%= f.input :treatment_state, input_html: { class: "form-control" }, label: false %>
  </div>

  <div class="col-12">
    <label class="form-label">Treatment Country</label>
    <%= f.input :treatment_country, input_html: { class: "form-control" }, label: false %>
  </div>

  <div class="col-12">
    <label class="form-label">Disease</label>
    <%= f.input :disease, input_html: { class: "form-control" }, label: false %>
  </div>

  <div class="col-12">
    <%= f.button :submit, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/nurse/patient_records/edit.html.erb
<div class="card">
  <div class="card-body">
    <h5 class="card-title">Edit Patient Record</h5>

    <%= render "patient_records/form" %>
  </div>
</div>

app/views/nurse/patient_records/index.html.erb
<div class="card">
  <div class="card-body">
    <h5 class="card-title">All Patients</h5>

    <%= link_to "New Patient Record", new_nurse_patient_record_path, class: "btn btn-sm mb-3 btn-primary float-end" %>

    <!-- Default Table -->
    <table class="table">
      <thead>
      <tr>
        <th scope="col">Patient Name</th>
        <th scope="col">Patient Address</th>
        <th scope="col">Disease</th>
        <th scope="col">Date of birth</th>
        <th scope="col">Blood group</th>
        <th scope="col" colspan="3">Actions</th>
      </tr>
      </thead>
      <tbody>
      <% @patient_records.each do |patient_record| %>
        <tr>
          <th scope="row"><%= patient_record.name %></th>
          <td><%= patient_record.user.city %>,<%= patient_record.user.state %>,<%= patient_record.user.country %></td>
          <td><%= patient_record.disease %></td>
          <td><%= patient_record.date_of_birth %></td>
          <td><%= patient_record.blood_group %></td>
          <td>
            <% unless patient_record.cured? %>
            <% if UserPatientRecord.find_by(user_id: current_user.id, patient_record_id: patient_record.id).nil? %>
              <% user_patient_records = UserPatientRecord.where(patient_record_id: patient_record.id) %>
              <% if can_pick_patient_as_nurse(user_patient_records) %>
                <a data-turbo-method="put" class="btn btn-sm btn-outline-primary" href="/nurse/patient_records/<%= patient_record.id %>/assign_to_nurse">Pick
                  as my patient</a>
              <% end %>
                <% end %>
            <% end %>
            <%= link_to "show", nurse_patient_record_path(patient_record), class: "btn btn-sm btn-info" %>

            <% if !UserPatientRecord.find_by(user_id: current_user.id, patient_record_id: patient_record.id).nil? || patient_record.user == current_user %>
              <%= link_to "Edit", edit_nurse_patient_record_path(patient_record), class: "btn btn-sm btn-primary" %>
              <a data-turbo-method="delete" class="btn btn-sm btn-outline-danger" href="/nurse/patient_records/<%= patient_record.id %>">Delete</a>
            <% end %>

          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/nurse/patient_records/new.html.erb
<div class="card">
  <div class="card-body">
    <h5 class="card-title">New Patient Record</h5>

    <%= render "patient_records/form" %>
  </div>
</div>

app/views/nurse/patient_records/show.html.erb
<div class="card">
  <div class="card-body">
    <h5 class="card-title">Patient Details</h5>

    <div class="row">
      <div class="col-md-2">
        <strong>
          Patient Name
        </strong>
      </div>
      <div class="col-md-10">
        <%= @patient_record.name %>
      </div>
    </div>

    <div class="row mt-3">
      <div class="col-md-2">
        <strong>
          Patient Address
        </strong>
      </div>
      <div class="col-md-10">
        <%= @patient_record.treatment_city %>,<%= @patient_record.treatment_state %>,<%= @patient_record.treatment_country %>
      </div>
    </div>

    <div class="row mt-3">
      <div class="col-md-2">
        <strong>
          Disease
        </strong>
      </div>
      <div class="col-md-10">
        <%= @patient_record.disease %>
      </div>
    </div>

    <div class="row mt-3">
      <div class="col-md-2">
        <strong>
          Blood group
        </strong>
      </div>
      <div class="col-md-10">
        <%= @patient_record.blood_group %>
      </div>
    </div>

    <div class="row mt-3">
      <div class="col-md-2">
        <strong>
          Date of birth
        </strong>
      </div>
      <div class="col-md-10">
        <%= @patient_record.date_of_birth %>
      </div>
    </div>

    <div class="row mt-3">
      <div class="col-md-2">
        <strong>
          Height
        </strong>
      </div>
      <div class="col-md-10">
        <%= @patient_record.height %>
      </div>
    </div>

    <div class="row mt-3">
      <div class="col-md-2">
        <strong>
          Weight
        </strong>
      </div>
      <div class="col-md-10">
        <%= @patient_record.weight %>
      </div>
    </div>

    <div class="row mt-3">
      <div class="col-md-2">
        <strong>
          Bed Id
        </strong>
      </div>
      <div class="col-md-10">
        <%= @patient_record.bed_id %>
      </div>
    </div>

    <div class="row mt-3">
      <div class="col-md-2">
        <strong>
          Treatment Area
        </strong>
      </div>
      <div class="col-md-10">
        <%= @patient_record.treatment_area %>
      </div>
    </div>

    <div class="row mt-3">
      <div class="col-md-2">
        <strong>
          Treatment City
        </strong>
      </div>
      <div class="col-md-10">
        <%= @patient_record.treatment_city %>
      </div>
    </div>

    <div class="row mt-3">
      <div class="col-md-2">
        <strong>
          Treatment Country
        </strong>
      </div>
      <div class="col-md-10">
        <%= @patient_record.treatment_country %>
      </div>
    </div>
    <% unless @patient_record.cured? %>
    <% if UserPatientRecord.find_by(user_id: current_user.id, patient_record_id: @patient_record.id).nil? %>
      <% user_patient_records = UserPatientRecord.where(patient_record_id: @patient_record.id) %>
      <% if can_pick_patient_as_nurse(user_patient_records) %>
        <a data-turbo-method="put" class="btn btn-sm btn-outline-primary mt-3" href="/nurse/patient_records/<%= @patient_record.id %>/assign_to_nurse">Pick as my patient</a>
      <% end %>
    <% end %>
      <% end %>

    <a href="/nurse/patient_records" class="btn btn-outline-primary mt-3 " style="margin-left: 5px;">Back</a>

  </div>
</div>