config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  resources :patient_records do
    resources :attachments
    resources :comments
    resources :treatments do
      resources :drugs
    end
    member do
      put :assign_to_doctor
    end
  end
  resources :general_drugs

  resources :my_patients
  resources :home, only: [:index]

  namespace :patient do
    resources :patient_records do
      resources :treatments, only: [:show]
    end
  end

  namespace :nurse do
    resources :general_drugs
    resources :my_patients
    resources :patient_records do
      resources :attachments
      resources :comments
      resources :treatments do
        resources :drugs
      end
      member do
        put :assign_to_nurse
      end
    end
  end

  root "home#index"
end

app/models/patient_record.rb
class PatientRecord < ApplicationRecord
  belongs_to :user

  enum status: [:not_started, :in_progress, :cured]

  has_many :user_patient_records, dependent: :destroy
  has_many :users, through: :user_patient_records
  has_many :comments, dependent: :destroy
  has_many :treatments, dependent: :destroy
  has_many :attachments, dependent: :destroy
end

app/controllers/nurse/patient_records_controller.rb
class Nurse::PatientRecordsController < Nurse::ApplicationController
  before_action :set_patient_record, only: [:show, :assign_to_nurse, :edit, :update, :destroy]
  def index
    @patient_records = PatientRecord.all
  end

  def new
    @patient_record = PatientRecord.new
  end

  def create
    @patient_record = PatientRecord.new(patient_records_params)
    @patient_record.user = current_user

    if @patient_record.save
      redirect_to nurse_patient_records_path, notice: "Patient record created successfully."
    else
      render :new
    end
  end

  def edit; end

  def update
    if @patient_record.update(patient_records_params)
      redirect_to nurse_patient_records_path, notice: "Patient record updated successfully."
    else
      render :edit
    end
  end


  def show; end

  def assign_to_nurse
    UserPatientRecord.find_or_create_by(user_id: current_user.id, patient_record_id: @patient_record.id)
    @patient_record.update_column(:status, "in_progress")
    redirect_to nurse_my_patients_path, notice: "Patient picked successfully."
  end

  def destroy
    if @patient_record.destroy
      redirect_to nurse_patient_records_path, notice: "Patient record destroyed successfully."
    else
      redirect_to nurse_patient_records_path, alert: @patient_record.errors.full_messages.join(",")
    end
  end

  private

  def set_patient_record
    @patient_record = PatientRecord.find(params[:id])
  end

  def patient_records_params
    params.require(:patient_record).permit(:name, :date_of_birth, :height, :weight, :bed_id, :blood_group, :treatment_area,
                                           :treatment_city, :treatment_state, :treatment_country, :disease, :status)
  end

end

app/controllers/patient/application_controller.rb
class Patient::ApplicationController < ApplicationController
  before_action :check_patient?

  def check_patient?
    redirect_to root_path, alert: "You are not authorized to perform this action."   unless current_user.role.slug == "patient"
  end
end

app/controllers/patient/patient_records_controller.rb
class Patient::PatientRecordsController < Patient::ApplicationController
  before_action :set_patient_record, only: [:update, :destroy, :show, :edit]

  def index
    @patient_records = PatientRecord.all
  end

  def new
    @patient_record = PatientRecord.new
  end

  def create
    @patient_record = PatientRecord.new(patient_records_params)
    @patient_record.user = current_user

    if @patient_record.save
      redirect_to patient_patient_records_path, notice: "Patient record created successfully."
    else
      render :new
    end
  end

  def edit; end

  def show; end

  def update
    if @patient_record.update(patient_records_params)
      redirect_to patient_patient_records_path, notice: "Patient record updated successfully."
    else
      render :edit
    end
  end

  def destroy
    if @patient_record.destroy
      redirect_to patient_patient_records_path, notice: "Patient record destroyed successfully."
    else
      redirect_to patient_patient_records_path, alert: @patient_record.errors.full_messages.join(",")
    end
  end

  private

  def set_patient_record
    @patient_record = PatientRecord.find(params[:id])
  end

  def patient_records_params
    params.require(:patient_record).permit(:date_of_birth, :height, :weight, :bed_id, :blood_group, :treatment_area,
                                           :treatment_city, :treatment_state, :treatment_country, :disease, :status)
  end
end

app/controllers/patient/treatments_controller.rb
class Patient::TreatmentsController < Patient::ApplicationController
  def show
    @treatment = Treatment.find(params[:id])
  end
end

app/controllers/patient_records_controller.rb
class PatientRecordsController < ApplicationController
  before_action :set_patient_record, only: [:show, :assign_to_doctor, :edit, :destroy, :update]
  def index
    @patient_records = PatientRecord.all
  end

  def show; end

  def new
    @patient_record = PatientRecord.new
  end

  def create
    @patient_record = PatientRecord.new(patient_records_params)
    @patient_record.user = current_user

    if @patient_record.save
      redirect_to patient_records_path, notice: "Patient record created successfully."
    else
      render :new
    end
  end

  def edit; end

  def assign_to_doctor
    UserPatientRecord.find_or_create_by(user_id: current_user.id, patient_record_id: @patient_record.id)
    @patient_record.update_column(:status, "in_progress")
    redirect_to my_patients_path, notice: "Patient picked successfully."
  end

  def update
    if @patient_record.update(patient_records_params)
      redirect_to patient_records_path, notice: "Patient record updated successfully."
    else
      render :edit
    end
  end

  def destroy
    if @patient_record.destroy
      redirect_to patient_records_path, notice: "Patient record destroyed successfully."
    else
      redirect_to patient_records_path, alert: @patient_record.errors.full_messages.join(",")
    end
  end

  private

  def set_patient_record
    @patient_record = PatientRecord.find(params[:id])
  end

  def patient_records_params
    params.require(:patient_record).permit(:name, :date_of_birth, :height, :weight, :bed_id, :blood_group, :treatment_area,
                                           :treatment_city, :treatment_state, :treatment_country, :disease, :status)
  end
end

app/helpers/patient_records_helper.rb
module PatientRecordsHelper
end

app/views/patient/patient_records/_form.html.erb
<%= simple_form_for @patient_record, url: @patient_record.new_record? ? patient_patient_records_path : patient_patient_record_path(@patient_record), html: { "data-turbo": false, class: "row g-3" } do |f| %>

  <div class="col-12">
    <label class="form-label">Date of birth</label>
    <%= f.input :date_of_birth, input_html: { class: "form-control" }, html5: true, label: false %>
  </div>

  <div class="col-12">
    <label class="form-label">Height</label>
    <%= f.input :height, input_html: { class: "form-control" }, label: false %>
  </div>

  <div class="col-12">
    <label class="form-label">Weight</label>
    <%= f.input :weight, input_html: { class: "form-control" }, label: false %>
  </div>

  <div class="col-12">
    <label class="form-label">Bed Id</label>
    <%= f.input :bed_id, input_html: { class: "form-control" }, label: false %>
  </div>

  <div class="col-12">
    <label class="form-label">Blood Group</label>
    <%= f.input :blood_group, input_html: { class: "form-control" }, label: false %>
  </div>

  <div class="col-12">
    <label class="form-label">Treatment Area</label>
    <%= f.input :treatment_area, input_html: { class: "form-control" }, label: false %>
  </div>

  <div class="col-12">
    <label class="form-label">Treatment City</label>
    <%= f.input :treatment_city, input_html: { class: "form-control" }, label: false %>
  </div>

  <div class="col-12">
    <label class="form-label">Treatment State</label>
    <%= f.input :treatment_state, input_html: { class: "form-control" }, label: false %>
  </div>

  <div class="col-12">
    <label class="form-label">Treatment Country</label>
    <%= f.input :treatment_country, input_html: { class: "form-control" }, label: false %>
  </div>

  <div class="col-12">
    <label class="form-label">Disease</label>
    <%= f.input :disease, input_html: { class: "form-control" }, label: false %>
  </div>

  <div class="col-12">
    <%= f.button :submit, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/patient/patient_records/edit.html.erb
<div class="card">
  <div class="card-body">
    <h5 class="card-title">Edit Patient Record</h5>

    <%= render "patient/patient_records/form" %>
  </div>
</div>

app/views/patient/patient_records/index.html.erb
<div class="card">
  <div class="card-body">
    <h5 class="card-title">Patient Records</h5>

    <%= link_to "New Patient Record", new_patient_patient_record_path, class: "btn btn-primary float-end" %>

    <!-- Default Table -->
    <table class="table">
      <thead>
      <tr>
        <th scope="col">Disease</th>
        <th scope="col">Height</th>
        <th scope="col">Weight</th>
        <th scope="col">Date of birth</th>
        <th scope="col">Blood group</th>
        <th scope="col" colspan="3">Actions</th>
      </tr>
      </thead>
      <tbody>
      <% @patient_records.each do |patient_record| %>
        <tr>
          <td  scope="row"><%= patient_record.disease %></td>
          <td><%= patient_record.height %></td>
          <td><%= patient_record.weight %></td>
          <td><%= patient_record.date_of_birth %></td>
          <td><%= patient_record.blood_group %></td>
          <td>
            <%= link_to "show", patient_patient_record_path(patient_record), class: "btn btn-sm btn-info" %>
            <%= link_to "Edit", edit_patient_patient_record_path(patient_record), class: "btn btn-sm btn-primary" %>
            <a data-turbo-method="delete" class="btn btn-sm btn-outline-danger" href="/patient/patient_records/<%= patient_record.id %>">Delete</a>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/patient/patient_records/new.html.erb
<div class="card">
  <div class="card-body">
    <h5 class="card-title">New Patient Record</h5>

    <%= render "patient/patient_records/form" %>
  </div>
</div>

app/views/patient/patient_records/show.html.erb
<div class="card">
  <div class="card-body">
    <h5 class="card-title">Patient Details</h5>

    <div class="row">
      <div class="col-md-2">
        <strong>
          Patient Name
        </strong>
      </div>
      <div class="col-md-10">
        <%= @patient_record.name %>
      </div>
    </div>

    <div class="row mt-3">
      <div class="col-md-2">
        <strong>
          Patient Address
        </strong>
      </div>
      <div class="col-md-10">
        <%= @patient_record.treatment_city %>,<%= @patient_record.treatment_state %>,<%= @patient_record.treatment_country %>
      </div>
    </div>

    <div class="row mt-3">
      <div class="col-md-2">
        <strong>
          Disease
        </strong>
      </div>
      <div class="col-md-10">
        <%= @patient_record.disease %>
      </div>
    </div>

    <div class="row mt-3">
      <div class="col-md-2">
        <strong>
          Blood group
        </strong>
      </div>
      <div class="col-md-10">
        <%= @patient_record.blood_group %>
      </div>
    </div>

    <div class="row mt-3">
      <div class="col-md-2">
        <strong>
          Date of birth
        </strong>
      </div>
      <div class="col-md-10">
        <%= @patient_record.date_of_birth %>
      </div>
    </div>

    <div class="row mt-3">
      <div class="col-md-2">
        <strong>
          Height
        </strong>
      </div>
      <div class="col-md-10">
        <%= @patient_record.height %>
      </div>
    </div>

    <div class="row mt-3">
      <div class="col-md-2">
        <strong>
          Weight
        </strong>
      </div>
      <div class="col-md-10">
        <%= @patient_record.weight %>
      </div>
    </div>

    <div class="row mt-3">
      <div class="col-md-2">
        <strong>
          Bed Id
        </strong>
      </div>
      <div class="col-md-10">
        <%= @patient_record.bed_id %>
      </div>
    </div>

    <div class="row mt-3">
      <div class="col-md-2">
        <strong>
          Treatment Area
        </strong>
      </div>
      <div class="col-md-10">
        <%= @patient_record.treatment_area %>
      </div>
    </div>

    <div class="row mt-3">
      <div class="col-md-2">
        <strong>
          Treatment City
        </strong>
      </div>
      <div class="col-md-10">
        <%= @patient_record.treatment_city %>
      </div>
    </div>

    <div class="row mt-3">
      <div class="col-md-2">
        <strong>
          Treatment Country
        </strong>
      </div>
      <div class="col-md-10">
        <%= @patient_record.treatment_country %>
      </div>
    </div>

    <% if @patient_record.in_progress? %>
      <a data-turbo-method="put" href="/patient/patient_records/<%= @patient_record.id %>?patient_record[status]=cured" class="btn btn-sm btn-outline-primary mt-3">Mark as Cured</a>
    <% end %>

  </div>
</div>

<div class="card">
  <div class="card-body">
    <h5 class="card-title">Comments</h5>

    <%= link_to "New Comment", new_patient_record_comment_path(@patient_record), class: "btn btn-primary float-end" %>

    <!-- Default Table -->
    <table class="table">
      <thead>
      <tr>
        <th scope="col">Comment</th>
        <th scope="col">Created Date</th>
        <th scope="col">Created by</th>
        <th colspan="2">Actions</th>
      </tr>
      </thead>
      <tbody>
      <% @patient_record.comments.each do |comment| %>
        <tr>
          <td><%= comment.comment %></td>
          <td><%= comment.added_at.to_datetime %></td>
          <td><%= comment.user&.name %>(<%= comment.user&.role&.name %>)</td>
          <td>
            <% if comment.user == current_user %>
              <%= link_to "Edit", edit_patient_record_comment_path(comment), class: "btn btn-sm btn-primary" %>
              <a class="btn btn-sm btn-outline-danger" href="/patient_records/<%= @patient_record.id %>/comments/<%= comment.id %>">Delete</a>
            <% end %>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

<div class="card">
  <div class="card-body">
    <h5 class="card-title">Treatments</h5>

    <!-- Default Table -->
    <table class="table">
      <thead>
      <tr>
        <th scope="col">Description</th>
        <th scope="col">Status</th>
        <th scope="col">Created Date</th>
        <th scope="col">Actions</th>
      </tr>
      </thead>
      <tbody>
      <% @patient_record.treatments.each do |treatment| %>
        <tr>
          <td><%= treatment.description %></td>
          <td><%= treatment.status %></td>
          <td><%= treatment.date %></td>
          <td><%= link_to "Show", patient_patient_record_treatment_path(@patient_record, treatment), class: "btn btn-sm btn-info" %></td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>